Workflow changes, hopefully used cached R environments

diff --git a/.github/workflows/notebook_check_python.yml b/.github/workflows/notebook_check_python.yml
--- a/.github/workflows/notebook_check_python.yml
+++ b/.github/workflows/notebook_check_python.yml
@@ -1,7 +1,6 @@
 name: Execute python notebooks
 
 on:
-
   pull_request:
   workflow_dispatch:
   schedule:
@@ -54,9 +53,7 @@ jobs:
       fail-fast: false
       matrix:
         notebook: ${{ fromJson(needs.setup.outputs.notebooks) }}
-    outputs:
-      notebook-status: ${{ steps.execute.outcome }}
-
+      
     steps:
     - id: checkout
       uses: actions/checkout@v3
@@ -90,28 +87,35 @@ jobs:
         
         if [ $? -ne 0 ]; then
           echo "Notebook ${{ matrix.notebook.name }} failed."
-          exit 1  # Explicitly mark this job matrix task as failed
+          echo "FAILED" > results-${{ matrix.notebook.name }}.txt
+          exit 1
+        else
+          echo "SUCCESS" > results-${{ matrix.notebook.name }}.txt
         fi
 
     - name: Upload results
       uses: actions/upload-artifact@v4
       with:
         name: notebook-results-${{ matrix.notebook.name }}
-        path: ${{ matrix.notebook.path }}
+        path: results-${{ matrix.notebook.name }}.txt
 
   post-check:
     runs-on: ubuntu-latest
     needs: execute-notebooks
     if: always()  # Run post-check no matter what
     steps:
-    - name: Check status of all notebooks
+    - name: Gather all notebook results
+      uses: actions/download-artifact@v4
+      with:
+        path: results/
+
+    - name: Check notebook results
       run: |
-        FAILED_COUNT=$(echo "${{ needs.execute-notebooks.outputs.notebook-status }}" | grep -c "failure")
+        FAILED_COUNT=$(grep -l "FAILED" results/*.txt | wc -l)
 
         if [ "$FAILED_COUNT" -gt 0 ]; then
           echo "At least one notebook has failed execution."
           exit 1  # Fail the workflow
+        else
+          echo "All notebooks executed successfully!"
         fi
-
-    - name: Report success
-      run: echo "All notebooks executed successfully!"
