Patch on post-check

diff --git a/.github/workflows/notebook_check_python_dev.yml b/.github/workflows/notebook_check_python_dev.yml
--- a/.github/workflows/notebook_check_python_dev.yml
+++ b/.github/workflows/notebook_check_python_dev.yml
@@ -91,16 +91,15 @@ jobs:
         if [ $EXIT_CODE -ne 0 ]; then
           echo "Notebook ${{ matrix.notebook.name }} failed."
           echo "FAILED" > results-${{ matrix.notebook.name }}.txt
+          exit 1  # Fail this step
         else
           echo "Notebook ${{ matrix.notebook.name }} succeeded."
           echo "SUCCESS" > results-${{ matrix.notebook.name }}.txt
         fi
-        
-        # Always exit with 0 so upload step runs
-        exit 0
 
     - name: Upload results
       uses: actions/upload-artifact@v4
+      if: always()
       with:
         name: notebook-results-${{ matrix.notebook.name }}
         path: results-${{ matrix.notebook.name }}.txt
